"""Tests for Human-in-the-Loop (Phase 2 / PRD V2.6 §10.6).

Red-Green TDD for:
  - Approve task (single + dual approval)
  - Reject task
  - Revise task (send back to configuring)
  - Review history & stats
"""

import pytest
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession
from src.models.task_orm import TaskORM
from src.services import human_in_loop as hil
from src.services import task_hub

pytestmark = pytest.mark.asyncio(loop_scope="function")


@pytest.fixture(autouse=True)
async def clear_db(db: AsyncSession):
    await db.execute(delete(TaskORM))
    await db.commit()
    hil._review_db.clear()
    hil._task_risk_db.clear()
    task_hub._clear_stores()
    yield


async def _create_task_in_human_wait(db: AsyncSession, workflow_template_id: str = "wf_001") -> task_hub.Task:
    t = await task_hub.create_task(db, "Review Me", workflow_template_id, 1, "acc_1", "pers_1", created_by="alice")
    await task_hub.configure(db, t.id)
    await task_hub.queue(db, t.id)
    await task_hub.start(db, t.id)
    await task_hub.wait_human(db, t.id)
    return await task_hub.get_task(db, t.id)


# ─── 1. Approve Task ───

async def test_approve_task(db: AsyncSession):
    t = await _create_task_in_human_wait(db)
    result = await hil.approve_task(db, t.id, "reviewer_1", publish_mode="immediate")
    assert result["status"] == "approved_waiting_publish"
    assert result["message"].startswith("审核已通过")
    assert (await task_hub.get_task(db, t.id)).status.value == "approved_waiting_publish"


async def test_dual_approval_requires_two_approvers(db: AsyncSession):
    t = await _create_task_in_human_wait(db, workflow_template_id="wf_publish")
    # First approval
    result1 = await hil.approve_task(db, t.id, "reviewer_1")
    assert result1["status"] == "human_wait"
    assert result1["message"].startswith("Primary approval")
    assert (await task_hub.get_task(db, t.id)).status.value == "human_wait"

    # Second approval
    result2 = await hil.approve_task(db, t.id, "reviewer_2")
    assert result2["status"] == "approved_waiting_publish"
    assert (await task_hub.get_task(db, t.id)).status.value == "approved_waiting_publish"


# ─── 2. Reject Task ───

async def test_reject_task(db: AsyncSession):
    t = await _create_task_in_human_wait(db)
    result = await hil.reject_task(db, t.id, "reviewer_1", reason="Violates brand guidelines")
    assert result["status"] == "REJECTED"
    assert result["reason"] == "Violates brand guidelines"
    assert (await task_hub.get_task(db, t.id)).status.value == "failed"


# ─── 3. Revise Task ───

async def test_revise_task(db: AsyncSession):
    t = await _create_task_in_human_wait(db)
    result = await hil.revise_task(
        db,
        t.id, "reviewer_1",
        target_node_index=2,
        revised_variables={"hook": "New hook text"},
        reason="Hook needs improvement",
    )
    assert result["status"] == "REVISED"
    assert result["target_node_index"] == 2
    assert (await task_hub.get_task(db, t.id)).status.value == "configuring"
    assert (await task_hub.get_task(db, t.id)).prompt_variables["hook"] == "New hook text"


# ─── 4. Pending Tasks ───

async def test_get_pending_tasks(db: AsyncSession):
    t = await _create_task_in_human_wait(db, workflow_template_id="wf_publish")
    pending = await hil.get_pending_tasks(db)
    assert len(pending) == 1
    assert pending[0].task_id == t.id
    assert pending[0].requires_dual_approval is True


async def test_get_review_detail(db: AsyncSession):
    t = await _create_task_in_human_wait(db, workflow_template_id="wf_publish")
    await task_hub.update_task(db, t.id, prompt_variables={"content_preview": "Hello world", "agent_summary": "Generated by AI"})
    detail = await hil.get_review_detail(db, t.id)
    assert detail["task_id"] == t.id
    assert detail["requires_dual_approval"] is True
    assert detail["has_primary_approval"] is False


# ─── 5. Review History ───

async def test_review_history(db: AsyncSession):
    t = await _create_task_in_human_wait(db)
    await hil.approve_task(db, t.id, "reviewer_1")
    history = await hil.get_review_history(db, t.id)
    assert len(history) == 1
    assert history[0].decision == "APPROVE"
    assert history[0].reviewer == "reviewer_1"


async def test_review_stats(db: AsyncSession):
    t1 = await _create_task_in_human_wait(db)
    t2 = await _create_task_in_human_wait(db)
    t3 = await _create_task_in_human_wait(db)
    await hil.approve_task(db, t1.id, "r1")
    await hil.reject_task(db, t2.id, "r2", "bad")
    await hil.revise_task(db, t3.id, "r3", 0, {}, "fix it")
    stats = await hil.get_review_stats(db)
    assert stats["approved"] == 1
    assert stats["rejected"] == 1
    assert stats["revised"] == 1
    assert stats["pending"] == 0  # all resolved


# ─── 6. Error Cases ───

async def test_approve_non_human_wait_raises(db: AsyncSession):
    t = await task_hub.create_task(db, "T", "wf", 1, "a", "p")
    await task_hub.configure(db, t.id)
    with pytest.raises(ValueError):
        await hil.approve_task(db, t.id, "reviewer_1")


async def test_reject_non_human_wait_raises(db: AsyncSession):
    t = await task_hub.create_task(db, "T", "wf", 1, "a", "p")
    with pytest.raises(ValueError):
        await hil.reject_task(db, t.id, "reviewer_1", reason="no")


# ─── 7. Integration: full review lifecycle ───

async def test_full_review_lifecycle(db: AsyncSession):
    # Create and run task to human wait
    t = await task_hub.create_task(
        db,
        name="Content Review",
        workflow_template_id="wf_publish",
        workflow_version=1,
        account_id="acc_1",
        persona_id="pers_1",
        prompt_variables={"content_preview": "Draft content here", "agent_summary": "Safe"},
        created_by="alice",
    )
    await task_hub.configure(db, t.id)
    await task_hub.queue(db, t.id)
    await task_hub.start(db, t.id)
    await task_hub.wait_human(db, t.id)

    # Check pending
    pending = await hil.get_pending_tasks(db)
    assert len(pending) == 1
    assert pending[0].task_name == "Content Review"

    # Detail view
    detail = await hil.get_review_detail(db, t.id)
    assert detail["content_preview"] == "Draft content here"

    # Dual approval
    r1 = await hil.approve_task(db, t.id, "alice")
    assert r1["status"] == "human_wait"
    r2 = await hil.approve_task(db, t.id, "bob")
    assert r2["status"] == "approved_waiting_publish"

    # History
    history = await hil.get_review_history(db, t.id)
    assert len(history) == 2
    assert history[0].is_dual_approval is True

    # Stats
    stats = await hil.get_review_stats(db)
    assert stats["approved"] == 2
    assert stats["pending"] == 0
